"""
Main entry point for MediaPipe + VTube Studio integration.
Coordinates the face tracking pipeline.
"""

import asyncio
import logging
import argparse

# Import local modules
from src.facetracker import FaceTracker
from src.vtube_client import VTubeStudioClient
from src.pipeline import capture_stage, tracking_stage, mapping_stage, injection_stage
from src.parameter_mapper import MEDIPIPE_TO_VTUBE, STANDARD_VTS_PARAMS, CUSTOM_PARAM_NAMES

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


async def main(host: str = "localhost", port: int = 8001, camera_id: int = 0,
                fps: int = 30, no_vtube: bool = False, debug: bool = False,
                force_calibration: bool = False):
    """
    Main application loop.

    Args:
        host: VTube Studio host.
        port: VTube Studio WebSocket port.
        camera_id: Camera device ID.
        fps: Target FPS for camera.
        no_vtube: If True, disable VTube Studio connection.
        debug: If True, enable debug mode with face landmarks visualization.
    """
    # Initialize components
    tracker = FaceTracker()
    
    # Check if calibration is needed
    import os
    calibration_file_exists = os.path.exists("eye_calibration.json")
    
    if force_calibration or not calibration_file_exists:
        if force_calibration:
            logger.info("Force calibration requested. Starting eye calibration...")
        else:
            logger.info("Calibration file not found. Starting eye calibration...")
        
        # Run eye calibration
        from src.eye_calibrator import calibrator
        from src.eye_calibrator import EyeCalibrationHelper
        calibration_helper = EyeCalibrationHelper(calibrator)
        calibration_result = await calibration_helper.run_calibration()
        if not calibration_result:
            logger.error("Калибровка не удалась, продолжение с настройками по умолчанию.")
        else:
            logger.info("Eye calibration completed successfully.")
    else:
        logger.info("Calibration file found. Skipping eye calibration.")
    
    # Check calibration quality
    from src.eye_calibrator import calibrator
    metrics = calibrator.calculate_calibration_quality()
    if calibrator.needs_recalibration():
        suggestions = calibrator.quality_checker.suggest_recalibration(metrics)
        logger.warning("Калибровка имеет низкое качество: %s", suggestions)
    
    logger.info("Старт основной части программы")
    
    # Initialize VTube Studio client only if --no-vtube is not specified
    client = None
    if not no_vtube:
        client = VTubeStudioClient(host=host, port=port)
        # Connect to VTube Studio
        if not await client.connect():
            logger.error("Failed to connect to VTube Studio. Make sure VTube Studio is running and API access is enabled.")
            return
        
        if not await client.authenticate():
            logger.error("Failed to authenticate with VTube Studio. Check plugin permissions.")
            return
        
        # Create custom parameters in VTube Studio if they don't exist
        # Standard VTube Studio parameters don't need to be created
        # Custom parameters (with 'custom_' prefix) need to be created
        logger.info("Creating custom parameters in VTube Studio...")
        
        # Get all unique parameter names that might be used
        all_param_names = set(MEDIPIPE_TO_VTUBE.values())
        
        # Create only non-standard parameters
        custom_params_created = 0
        for param_name in all_param_names:
            if param_name not in STANDARD_VTS_PARAMS:
                success = await client.create_parameter(param_name)
                if success:
                    custom_params_created += 1
                else:
                    logger.warning(f"Failed to create parameter {param_name}. It may already exist.")
        
        # Also create custom parameters that might be generated by the mapper
        # These are parameters with 'custom_' prefix
        # We'll create a few example custom parameters to ensure the system works

        for param_name in CUSTOM_PARAM_NAMES:
            success = await client.create_parameter(param_name)
            if success:
                custom_params_created += 1
            elif "already exists" not in str(success).lower():
                logger.warning(f"Failed to create custom parameter {param_name}")
        
        logger.info(f"Created {custom_params_created} custom parameters in VTube Studio")
            
        # Add delay after creating parameters to ensure they are registered
        await asyncio.sleep(1.0)  # Small delay to ensure connection is stable
    
    logger.info("Starting face tracking pipeline...")
    
    # Create the pipeline stages
    frame_stream = capture_stage(device_id=camera_id, fps=fps)
    tracking_stream = tracking_stage(frame_stream, tracker, draw_landmarks=debug)
    mapping_stream = mapping_stage(tracking_stream)
    
    # Run the injection stage
    try:
        await injection_stage(mapping_stream, client, fps, draw_landmarks=debug)
    except KeyboardInterrupt:
        logger.info("Shutting down...")
    except Exception as e:
        logger.error("Unexpected error in main loop: %s", e, exc_info=True)
    finally:
        if client is not None:
            try:
                await client.close()
            except Exception as e:
                logger.error("Error during client cleanup: %s", e)

async def async_generator_wrapper(sync_gen):
    """Wrapper to use synchronous generator in async context."""
    loop = asyncio.get_event_loop()
    try:
        while True:
            # Run next() in thread pool to avoid blocking
            item = await loop.run_in_executor(None, lambda: next(sync_gen, (False, None)))
            if item == (False, None):
                break
            yield item
    except StopIteration:
        pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Live2D avatar control via webcam")
    parser.add_argument("--host", type=str, default="localhost", help="VTube Studio host")
    parser.add_argument("--port", type=int, default=8001, help="VTube Studio WebSocket port")
    parser.add_argument("--camera", type=int, default=0, help="Camera device ID")
    parser.add_argument("--fps", type=int, default=30, help="Camera FPS")
    parser.add_argument("--debug", action="store_true", help="Enable debug mode with face landmarks visualization")
    parser.add_argument("--no-vtube", action="store_true", help="Disable VTube Studio connection and run in standalone debug mode")
    parser.add_argument("--calibrate", action="store_true", help="Force eye calibration even if calibration file exists")
    
    args = parser.parse_args()
    
    # Run the async main function
    try:
        asyncio.run(main(args.host, args.port, args.camera, args.fps, args.no_vtube, args.debug, args.calibrate))
    except KeyboardInterrupt:
        print("\nShutting down...")
    except Exception as e:
        print(f"Error: {e}")
        
    # Ensure clean shutdown
    import sys
    sys.exit(0)  # Already closed in main's finally block
